version: "3.8"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: carbon_mvp
      POSTGRES_USER: carbon
      POSTGRES_PASSWORD: carbon
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
